### ISSUE TITLE
Deprecated function: explode(): Passing null to parameter #2 ($string) of type string is deprecated

### ISSUE THREAD

**Issue by mstenta** [Rothamsted-Ecoinformatics/farm_rothamsted#532] opened 2023-08-11 13:55 UTC
This error appeared last night in logs, coming from the spraying quick form:

```
Deprecated function: explode(): Passing null to parameter #2 ($string) of type string is deprecated in Drupal\file\Element\ManagedFile::uploadAjaxCallback() (line 184 of /opt/drupal/web/core/modules/file/src/Element/ManagedFile.php) #0 /opt/drupal/web/core/includes/bootstrap.inc(347): _drupal_error_handler_real()
#1 [internal function]: _drupal_error_handler()
#2 /opt/drupal/web/core/modules/file/src/Element/ManagedFile.php(184): explode()
#3 [internal function]: Drupal\file\Element\ManagedFile::uploadAjaxCallback()
#4 /opt/drupal/web/core/lib/Drupal/Core/Form/FormAjaxResponseBuilder.php(69): call_user_func_array()
#5 /opt/drupal/web/core/lib/Drupal/Core/Form/EventSubscriber/FormAjaxSubscriber.php(109): Drupal\Core\Form\FormAjaxResponseBuilder->buildResponse()
#6 [internal function]: Drupal\Core\Form\EventSubscriber\FormAjaxSubscriber->onException()
#7 /opt/drupal/web/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(142): call_user_func()
#8 /opt/drupal/vendor/symfony/http-kernel/HttpKernel.php(229): Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch()
#9 /opt/drupal/vendor/symfony/http-kernel/HttpKernel.php(92): Symfony\Component\HttpKernel\HttpKernel->handleThrowable()
#10 /opt/drupal/web/modules/simple_oauth/src/HttpMiddleware/BasicAuthSwap.php(68): Symfony\Component\HttpKernel\HttpKernel->handle()
#11 /opt/drupal/web/core/lib/Drupal/Core/StackMiddleware/Session.php(58): Drupal\simple_oauth\HttpMiddleware\BasicAuthSwap->handle()
#12 /opt/drupal/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(48): Drupal\Core\StackMiddleware\Session->handle()
#13 /opt/drupal/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(48): Drupal\Core\StackMiddleware\KernelPreHandle->handle()
#14 /opt/drupal/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(51): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle()
#15 /opt/drupal/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle()
#16 /opt/drupal/web/core/lib/Drupal/Core/DrupalKernel.php(718): Stack\StackedHttpKernel->handle()
#17 /opt/drupal/web/index.php(19): Drupal\Core\DrupalKernel->handle()
#18 {main}.
```

**Comment by paul121** [comment] 2023-08-14 15:39
Interesting.. this error is coming from Drupal core. I searched the issue queue but didn't see anything there. The relevant code is interesting:

```php
  public static function uploadAjaxCallback(&$form, FormStateInterface &$form_state, Request $request) {
    /** @var \Drupal\Core\Render\RendererInterface $renderer */
    $renderer = \Drupal::service('renderer');

    $form_parents = explode('/', $request->query->get('element_parents')); #line 184
 ```

So it seems that the file upload AJAX request did not include the `element_parents` query parameter? I'm not sure why this might happen. Perhaps the user's device/browser is older and hits a JS error when building the `element_parents` and sending the AJAX request? We don't do anything "special" with the ManagedFile uploads in these quick forms.

I can't replicate the error, but can see the working URL that is used when uploading a file: `https://rothamsted.ddev.site/quick/spraying?element_parents=products/product_labels&ajax_form=1&_wrapper_format=drupal_ajax&_wrapper_format=drupal_ajax`

**Comment by paul121** [comment] 2023-08-14 15:40
@mstenta could you monitor and let us know if we see this error again? If my theory is correct we might be able to pin it down to a single user's device/browser too.

**Comment by mstenta** [comment] 2023-08-14 15:55
Some more info from my logs:

This error occurred 3 times on August 11th on the Brooms Barn instance with uid 170, and 8 times on August 14th on the Harpenden instance with uid 112. All were on the Spraying quick form.

The user agent information for each were (respectively):

- `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36`
- `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.183`

**Comment by paul121** [comment] 2023-08-14 16:47
Hmm. Nothing really standing out to me. Lets chat on Tuesday

**Comment by aislinnpearson** [comment] 2023-08-22 11:22
> @mstenta could you monitor and let us know if we see this error again? If my theory is correct we might be able to pin it down to a single user's device/browser too.

Hmmm... I think I might know who this user is. Matt was having problems visualising the spraying quick form on his PC. He wanted to add multiple products but couldn't - when I tried on my computer there were no problems with the quick form. 

Maybe his browser is out of date and needs updating... I'll double check and then maybe get him to re-enter the log to see if it generates the same issue.

**Comment by aislinnpearson** [comment] 2023-08-22 16:17
Can't reproduce this error so closing this issue. If it comes up again, we can re-open it.

**Closed as not planned by aislinnpearson** 2023-08-22 16:17 UTC
Labels: bug, Drupal core
