### ISSUE TITLE
Error uploading experiments with non UTF-8 characters

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#245] opened 2022-08-02 15:22 UTC
Hi @paul121 

I can't seem to upload the attached experiment. I can upload all the files without error messages, but when I press 'submit' I get the following error: 

![image](https://user-images.githubusercontent.com/16349781/182409453-87a978c5-d0d3-476c-aecf-146488afdd05.png)

I've double checked everything, and tried remaking the GIS files from scratch (initially the plot numbers weren't in sequential order and it didn't seem to like this), but even when I resolved that I can't get past this error. I get the error on the platformsh site as well as rothamsted.farmos.net.

However, I tried downloading and re-uploading the test files from the 2.5.x platformsh site, and they work just fine. 

Could you have a look and see if you can find where I am going wrong? It may well be me, and I just can't see the wood for the trees any more.

Thank you so much Paul! And sorry to bother you.

[2023-R-CS-790_farmos-error.zip](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/files/9243491/2023-R-CS-790_farmos-error.zip)

**Comment by paul121** [comment] 2022-08-03 04:37
Well this was a wacky error. TLDR, the `columns.csv` had malformed UTF-8 characters or was encoded incorrectly. Simply opening & resaving the CSV in libreoffice calc fixed the issue. 

@aislinnpearson if you can try your upload with this file I think it will work: [2023-R-CS-790_columns.csv](https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/files/9247945/2023-R-CS-790_columns.csv)

Is there anything special about how the `columns.csv` is created as compared to the `column-levels.csv`? Maybe a different program? Also, I'm curious if you got this error on other experiment plans as well or only this one (is this a consistent issue?)

Long version, here's what I found:

1. Drupal is logging this error message, which is actually an error message saying it is building the error message incorrectly (?!):

> Error: Wrong parameters for Drupal\Core\Database\DatabaseExceptionWrapper([string $message [, long $code [, Throwable $previous = NULL]]]) in Exception->__construct() (line 103 of /app/web/core/lib/Drupal/Core/Database/Driver/pgsql/Insert.php)

2. This bug has been fixed in Drupal 9.4: https://www.drupal.org/project/drupal/issues/3255437#comment-14560199

3. I applied that patch myself to reveal the *real* error message, which clears up that the `plan.column_descriptors` JSON data is incorrect.

> Drupal\Core\Entity\EntityStorageException: SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for type json LINE 1: ... VALUES ('18', '30', 'rothamsted_experiment', '0', 'en', '') ^ DETAIL: The input string ended unexpectedly. CONTEXT: JSON data

4. In my debugger I was able to see that `Json::encode($data)` was returning `FALSE`. It turns out you can get the last json error message with `json_last_error_msg()` function. This revealed the actual error:

> Malformed UTF-8 characters, possibly incorrectly encoded

5. A potential solution is to use this flag (I confirmed this works but still... weird thing for us to do?): `json_encode($data), JSON_INVALID_UTF8_SUBSTITUTE);` (source: https://stackoverflow.com/a/65327586)

**Comment by paul121** [comment] 2022-08-03 04:56
Aha!

@aislinnpearson  this is the `ontology_description` for column ID `PECO_0007241` (notice the weird characters): 

> A plant chemical exposure (PECO:0007189) involving a plant nutrient or a combination of plant nutrients.�[�PECO�:�cooperl�Gramene�:�pankaj_jaiswal�]

This is exactly how the description appeared in my spreadsheet program. I'm assuming you copy-pasted this from an HTML website somewhere and maybe copied parts that aren't raw text? It's possible this row might display nicer in another program and thus be easier to miss without the weird symbols.

So the solution... 
- We could do option 5 above, which just covers up the problem by replacing/removing the bad characters.
- OR we could potentially validate that the uploaded CSVs only contain UTF-8 characters. And we could display a *nice* error message when they don't (instead of a white screen :smile:!)

@mstenta I'm curious if you have any ideas/opinions on the best way to solve this... kinda curious if this could be a larger issue for CSV imports more generally, but this error is only raised because `Json::encode()` doesn't like the non UTF-8 characters, not the database. But maybe we should try saving non UTF-8 characters to an asset name/description and see what happens?

**Comment by aislinnpearson** [comment] 2022-08-03 08:19
HI @paul121 

> I'm assuming you copy-pasted this from an HTML website somewhere and maybe copied parts that aren't raw text? It's possible this row might display nicer in another program and thus be easier to miss without the weird symbols.

Yes. This is exactly what I did. Thank you so much for figuring it out! 

> Also, I'm curious if you got this error on other experiment plans as well or only this one (is this a consistent issue?)

It definitely exists in a few of the definitions (it's where someone quotes an original source in the description of a term). It's easy enough to remove. I just hadn't tried any of the other files yet because I spent most of yesterday trying to figure out what I was doing wrong. I would never have figured this out! 

For the solution, I was wondering if it might be a combination of the two options you have above:
1. Remove the bad characters
2. Tell the user you did this and highlight them

I'm just thinking that most people might not understand what UTF-8 characters are. I certainly didn't before this, and I've just done a bit of googling now. Also I don't know if this is relevant to the solution but in future most of the terms would ideally pull from the ontology API into a managed taxonomy, but obviously we haven't reached that point in our development yet...

Thank you so much for figuring it out @paul121 - I cannot tell you how confusing this got yesterday!

**Comment by paul121** [comment] 2022-08-03 17:17
> For the solution, I was wondering if it might be a combination of the two options you have above:
> Remove the bad characters
> Tell the user you did this and highlight them

Interesting... that may be possible but would really take a lot to figure out :-/

> I'm just thinking that most people might not understand what UTF-8 characters are. I certainly didn't before this, and I've just done a bit of googling now.

This is an important point. Perhaps we should go with option 5 above and replace/remove these errant values without telling the user. Non UTF-8 characters are uncommon and removing them shouldn't break the readability of the string. If this caused any issues, they could be edited later on via #207.

**Comment by aislinnpearson** [comment] 2022-08-04 08:20
Hi @paul121 

> Perhaps we should go with option 5 above and replace/remove these errant values without telling the user. 

Sounds good to me - especially if that is a reasonably easy fix? We'll know how much of an issue it becomes with the uploading of trials in the next few weeks, and then you are right. We can address it in that later issue. The important thing is that I got the experiment into the Platformsh site yesterday and it's just being checked now, ready to go live on the RRES site. :)

**Closed as completed** 2022-08-05 15:57 UTC
Labels: bug
