### ISSUE TITLE
Bug: Single product quantity not saving

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#297] opened 2022-09-20 15:13 UTC
Hi @paul121, @mstenta 

I had a long chat with Had today and we noticed that the quantities from the quick forms aren't saving properly. We noticed what I think are three separate issues, but I included them all here in case they are linked somehow:

1. **Fertiliser Quick Form:** The materials are saving to the record name, but not the application rate. Here is an example quick form I submitted:

![image](https://user-images.githubusercontent.com/16349781/191292398-e97e99ac-9349-4fa6-9cb3-c91b9d1da92f.png)

![image](https://user-images.githubusercontent.com/16349781/191292657-e909c0db-2700-4ce0-abe4-4cc3395d3b9d.png)

2. **Spraying Quick Form:** Again the material is saving to the notes (the batch number is saved), but not the application rate:
![image](https://user-images.githubusercontent.com/16349781/191293455-283785d6-bf7a-4663-abf3-6930c459e604.png)

However, this issue appears to have been fixed as here is a log from today with the application rates saved:

![image](https://user-images.githubusercontent.com/16349781/191293890-dbbba9af-1b09-4968-af18-b0eb269136b2.png)

3. **Material Quantities:** I think this is then a legacy issue from 1.x but I think we also found an issue where the quantities saved are correct, but (1) the material terms aren't linked with the label _and_ (2) the same material is selected three times, rather than three unique materials (Had found some records where the materials were correct but they weren't linked to the label, so I am not sure if this is two separate issues)

![image](https://user-images.githubusercontent.com/16349781/191296108-f0771daf-0eea-424a-b400-217b91d9a0c5.png)

Had also noticed that the label gets a bit confusing with material quantities, and I was wondering if you could please explain how that logic works.

Thanks both

**Comment by paul121** [comment] 2022-09-20 16:18
Number 1/2 seem to be related to https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues/249, a material quantity is not created for the product if only a single product is added.

**Comment by paul121** [comment] 2022-09-20 17:50
Confirmed, the bug seen in 1/2 is that if only a single product was added, the quantity was not created when the form was submitted (case 1). If multiple products were added then they were both submitted (case 2).

This was quite similar to #249 , sorry @aislinnpearson that I didn't catch this. I've tested my change but would be good if you could test on the demo site and make sure it is working for you as well. Close this issue once you approve?

Re: case 3, we identified with @mstenta that this is an artifact of the migration from farmOS 1.x. Previously we did not have the ability to create a log that had quantities associated with multiple material terms. This is because the log referenced material terms separately from the quantities, so there was no way to link a quantity to a material term. For the Rothamsted use-case, however, we can assume that quantities had a label equal to the material term's name. SO we could clean some of this up with an update hook for Rothamsted instances specifically. I'll open a new issue for this.

**Comment by aislinnpearson** [comment] 2022-09-23 11:14
Hey @paul121 

So testing each of the quick forms now. I'll post a comment for each one if that is okay (otherwise I get distracted and lose my train of thought, and close the tab).

- [ ] **Drilling Quick Form:**

I can't enter anything here - this is unusual in that the starting quantity is zero (the fertiliser and pesticide quick form assume at least one quantity)

![image](https://user-images.githubusercontent.com/16349781/191948706-edf81e19-0c38-4cc7-88df-8e12cf4618cf.png)

**Comment by aislinnpearson** [comment] 2022-09-23 11:22
- [ ] **Fertiliser, compost and manure**

One quantity works well: https://2-7-b6xvjry-2mu45anerqtvq.uk-1.platformsh.site/log/12
Two quantities work well: https://2-7-b6xvjry-2mu45anerqtvq.uk-1.platformsh.site/log/14

But I noticed you get an error message when you try to upload any files: 

![image](https://user-images.githubusercontent.com/16349781/191949438-1b15e8f5-bd04-4e48-aaa0-f768941af566.png)

![image](https://user-images.githubusercontent.com/16349781/191949498-aa826759-0d7a-4501-91b8-f7247f33bd4c.png)

Although the do get added to the log:

![image](https://user-images.githubusercontent.com/16349781/191949991-648d6d19-a1c1-4dda-b889-16355ba045dc.png)
![image](https://user-images.githubusercontent.com/16349781/191950112-392062e8-593b-4059-8da3-281936c857e0.png)

**Comment by aislinnpearson** [comment] 2022-09-23 11:29
- [ ] **Spraying Quick Form**

I couldn't add more than one product:

![image](https://user-images.githubusercontent.com/16349781/191951005-9e7df242-ca2f-420c-a7df-d742fb8d2b48.png)

And when I tried to select only one product I got the below:

![image](https://user-images.githubusercontent.com/16349781/191950946-1d1b353d-1414-4953-af5a-3ce9d6786d4c.png)

**Comment by aislinnpearson** [comment] 2022-09-23 14:02
- [ ] Harvest Trailer and Bale Weights Quick Form

One quantity works: https://2-7-b6xvjry-2mu45anerqtvq.uk-1.platformsh.site/log/15
Two or more quantities works: https://2-7-b6xvjry-2mu45anerqtvq.uk-1.platformsh.site/log/16

But there is the same issue with the records (again saved to the log though: https://2-7-b6xvjry-2mu45anerqtvq.uk-1.platformsh.site/log/15):

![image](https://user-images.githubusercontent.com/16349781/191977130-37b4e3b6-04e4-4cf0-b689-69463c2624f2.png)
![image](https://user-images.githubusercontent.com/16349781/191977212-207518b1-0746-4011-a339-8262ca48d455.png)

**Comment by paul121** [comment] 2022-09-23 14:51
Thanks for testing @aislinnpearson I'll get this fixed today. These all seem to be related to the product count.

I'll make sure to test 0, 1 and multiple products across the quick forms. As well as uploading a file during the process of adding products. I believe this is "resetting" the product count (at a technical level) and causing those errors

**Comment by paul121** [comment] 2022-09-26 05:23
The problem is related to #126 , except that this time when a file is uploaded we are not losing the "Product count" from the form state, but the "Product type" instead. This causes an error for the "Product" field because the form does not think a "Product type" was selected, so thus the selected "Product" is invalid. The fix is to extend the tick of saving the temporary "Product type" to the form storage, just like we do for the "Product count".

@aislinnpearson I believe I was able to reproduce everything I see in your screenshots. It's tricky because the error message will appear differently depending on the order that fill you out the form. A bit of a technical explanation for future reference... basically, once you upload a file to the form, we loose the "form state values" but not the "form state storage", which causes the form (as currently implemented) to be in a broken state. It is the next "action" you take that will raise an error if it performs an AJAX request and triggers a form validation error for the "Product type" field, as is happening when changing the "Product count".

**Comment by paul121** [comment] 2022-09-26 05:32
I was also able to reproduce this in the AJAX dependent dropdown example that is a part of drupal/examples: https://www.drupal.org/project/examples/issues/3311557

It just seems so odd that this is only an issue when using the `managed_file` field. I've only been able to find a few mentions of this online and all without a solution. I landed on the solution we are currently using after digging into the drupal core Field Widget code (because obviously the `managed_file `field works in entity forms?) and found that it saves state to the "form state storage": https://git.drupalcode.org/project/drupal/-/blob/9.5.x/core/lib/Drupal/Core/Field/WidgetBase.php#L503

I would like to understand why this `managed_file` element needs to rebuild the form state anyways.... it would be nice if it could just be removed, but it must be there for a reason. It seems that this edge-cases needs to be better documented for developers building custom forms.

**Comment by aislinnpearson** [comment] 2022-09-26 08:46
Hi @paul121,

I see what you mean. I just had a play with the drilling quick form in 2.7.x again and it works if you do the products _before_ the label, but not after.

This concerns me in terms of testing the quick forms if we make any changes in future. Do you think it would help to move the files to the end of the quick forms? It's a bit annoying for drilling, but would work for everything else.

Otherwise, I was wondering if that idea of 'submitting' and saving as an 'in progress' draft would work... but that seems like a massive change. One to talk about tomorrow perhaps. Thanks for dealing with this issue at least.

**Comment by aislinnpearson** [comment] 2022-09-26 11:59
Hey @paul121,

So I was just playing around with the quick forms on 2.7.x on the platform.sh site for a separate issue. I wanted to submit a record for plots in an experiment. I went through the normal route of selecting plots in the experiment module, filled in the operations quick form and when I went to submit, I got the below:

![image](https://user-images.githubusercontent.com/16349781/192270476-e758eb9d-ff23-4bd0-8fa5-08276f59bdaa.png)

The issue that just creates more issues... I have a meeting between 3 and 4pm today, but let me know if you want to chat on Teams this evening and we can test it together. Alternatively something we need to probably talk about tomorrow. 

May the force be with us. :)

**Comment by paul121** [comment] 2022-09-26 16:07
> This concerns me in terms of testing the quick forms if we make any changes in future. Do you think it would help to move the files to the end of the quick forms?

Yeah the file upload does make this more challenging to test. Moving them to the end could help avoid errors but only if they are actually uploaded as the last action before submitting the form, so it still isn't a guarantee.

I think we should keep the file uploads where they are - we should be able to fix this bug, but will need to be more diligent in testing these parts of the quick form when we change  1) Any field associated with an AJAX operation or 2) The file upload mechanics.

>  I wanted to submit a record for plots in an experiment. I went through the normal route of selecting plots in the experiment module, filled in the operations quick form and when I went to submit, I got the below:

Hmm I am seeing this now as well.. The `location` is disabled when the form is initially loaded, but then appears again when the form is submitted. Notably it happens without uploading a file, so might be unrelated to other things we are chatting about here.

**Comment by paul121** [comment] 2022-09-27 19:35
I've opened a new issue

**Closed as completed by paul121** 2022-09-27 19:35 UTC
Labels: bug, Backwards compatibility
