### ISSUE TITLE
Experiment Module: Limit where plots are displayed

### ISSUE THREAD

**Issue by aislinnpearson** [Rothamsted-Ecoinformatics/farm_rothamsted#339] opened 2022-11-14 15:46 UTC
We've noticed that there has been a slowing in the processing speed of FarmOS. This is partly due to broadband/ wifi speeds but in addition a discussion with @paul121 and @mstenta we agreed that we could try to limit the locations where plots are displayed (i.e. only on the plots tab associated with the experiment). This should hopefully help the speed at which the plot and other farm graphics can be displayed. 

See also #336 

Marked as 'should do' as this isn't currently affecting our ability to use FarmOS, only the speed at which plots display/ upload

**Comment by paul121** [comment] 2022-11-14 20:18
@aislinnpearson this should be fixed with #336 and #334

Let's leave this issue open until we have the next release deployed and you can confirm that this solved the issue!

**Comment by paul121** [comment] 2022-11-14 20:20
We could consider updating or removing the `assets/plots` page as well. The issue is that this page will try and show all plots which will just take a long time. It may/may not make sense to view "all plots" together outside the context of an experiment? Or maybe we could add a filter to this page that makes you select the Experiment(s) you are interested in?

**Comment by aislinnpearson** [comment] 2022-11-15 14:39
> Let's leave this issue open until we have the next release deployed and you can confirm that this solved the issue!

Thanks @paul121 - I was wondering about this yesterday but thought it was better to make the issue than forget about it. I've moved it to the current milestone and assigned it to myself so I remember to check it.

> We could consider updating or removing the assets/plots page as well. The issue is that this page will try and show all plots which will just take a long time. It may/may not make sense to view "all plots" together outside the context of an experiment? Or maybe we could add a filter to this page that makes you select the Experiment(s) you are interested in?

I'm trying to think this through in my head. There may be situations where we want to apply an action to many plots - for example, if we are archiving many experiments - but would it make sense to visualise them? Probably not, but I'm aware I might end up asking you to undo this because we haven't yet had a use case for it. If we do remove the plot visualisation, does that mean other pages will render a bit quicker? Or does it only affect the assets/plots page @paul121? Maybe on to discuss on the call this evening...

**Comment by paul121** [comment] 2022-11-15 16:33
>  If we do remove the plot visualisation, does that mean other pages will render a bit quicker? Or does it only affect the assets/plots page @paul121?

Good question. Removing the assets/plots page will only affect that page, it won't make other pages render quicker.

**Comment by paul121** [comment] 2022-11-29 18:11
@aislinnpearson I believe we can close this, yes? https://github.com/Rothamsted-Ecoinformatics/farm_rothamsted/issues/334#issuecomment-1330806667

Overall I think we should just remove the `assets/plots` page altogether. It will probably be an uphill battle getting that to work, instead we should use `plan/#/plots` to see the plots associated with a plan.

**Closed as completed by paul121** 2022-11-29 18:11 UTC
Labels: Experiment Module, Priority 2: Should do (after must do's), Visualisation

**Comment by aislinnpearson** [comment] 2022-11-30 10:44
Hi @paul121,

> Overall I think we should just remove the assets/plots page altogether. It will probably be an uphill battle getting that to work, instead we should use plan/#/plots to see the plots associated with a plan.

I agree. Do you want me to create an issue for it? Not sure how to prioritise it... is it a quick easy fix which will also help with rendering (I assume not but wanted to ask just in case) and so worth doing while we are thinking about it? OR is it a bigger fix that needs more time, in which case if it's not doing any harm I'd prefer to deal with it a bit later...
